import { MasonryImage } from "@/components/photography/MasonryLayout";
import { PATH_PHOTOGRAPHY_IMAGES } from "@/lib/constants";

export const photos: MasonryImage[] = [
  {
    src: `${PATH_PHOTOGRAPHY_IMAGES}/Angel-3-15-25.jpg`,
    alt: "A picture of an angel statue in a park in Montreal, Canada.",
    location: "Montreal, Canada",
    year: "2025",
    size: [3024, 4032],
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAKAAoDASIAAhEBAxEB/8QAFAABAAAAAAAAAAAAAAAAAAAABf/EACUQAAECBQIHAQAAAAAAAAAAAAECAwAEBQYREiETIiMyQVORof/EABQBAQAAAAAAAAAAAAAAAAAAAAT/xAAXEQEBAQEAAAAAAAAAAAAAAAABABEh/9oADAMBAAIRAxEAPwAtNt0p2g1CedcTxA23oJONxgqH7iDZmSlBMuhtWUBZ0nHjMDUDqWfcC3OdWWN1bnvgMuuexf0wREzsoB2//9k=",
  },
  {
    src: `${PATH_PHOTOGRAPHY_IMAGES}/Athena-10-17-24.jpg`,
    alt: "A picture of an Athena statue in Copenhagen, Denmark.",
    location: "Copenhagen, Denmark",
    year: "2024",
    size: [3024, 4032],
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAKAAoDASIAAhEBAxEB/8QAFAABAAAAAAAAAAAAAAAAAAAABf/EACUQAAECBQIHAQAAAAAAAAAAAAECAwAEBQYREiETIiMyQVORof/EABQBAQAAAAAAAAAAAAAAAAAAAAT/xAAXEQEBAQEAAAAAAAAAAAAAAAABABEh/9oADAMBAAIRAxEAPwAtNt0p2g1CedcTxA23oJONxgqH7iDZmSlBMuhtWUBZ0nHjMDUDqWfcC3OdWWN1bnvgMuuexf0wREzsoB2//9k=",
  },
  {
    src: `${PATH_PHOTOGRAPHY_IMAGES}/Beluga-8-28-24.jpg`,
    alt: "A picture of a Beluga whale at Marineland in Niagara Falls, Canada.",
    location: "Niagara Falls, Canada",
    year: "2024",
    size: [3024, 4032],
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAKAAoDASIAAhEBAxEB/8QAFAABAAAAAAAAAAAAAAAAAAAABf/EACUQAAECBQIHAQAAAAAAAAAAAAECAwAEBQYREiETIiMyQVORof/EABQBAQAAAAAAAAAAAAAAAAAAAAT/xAAXEQEBAQEAAAAAAAAAAAAAAAABABEh/9oADAMBAAIRAxEAPwAtNt0p2g1CedcTxA23oJONxgqH7iDZmSlBMuhtWUBZ0nHjMDUDqWfcC3OdWWN1bnvgMuuexf0wREzsoB2//9k=",
  },
  {
    src: `${PATH_PHOTOGRAPHY_IMAGES}/Biodome-1-19-25.jpg`,
    alt: "A picture of the Biodome in Montreal, Canada.",
    location: "Montreal, Canada",
    year: "2025",
    size: [3024, 4032],
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAKAAoDASIAAhEBAxEB/8QAFAABAAAAAAAAAAAAAAAAAAAABf/EACUQAAECBQIHAQAAAAAAAAAAAAECAwAEBQYREiETIiMyQVORof/EABQBAQAAAAAAAAAAAAAAAAAAAAT/xAAXEQEBAQEAAAAAAAAAAAAAAAABABEh/9oADAMBAAIRAxEAPwAtNt0p2g1CedcTxA23oJONxgqH7iDZmSlBMuhtWUBZ0nHjMDUDqWfcC3OdWWN1bnvgMuuexf0wREzsoB2//9k=",
  },
  {
    src: `${PATH_PHOTOGRAPHY_IMAGES}/BunkerHill-12-15-24.jpg`,
    alt: "A picture of the Bunker Hill Monument in Boston, United States.",
    location: "Boston, United States",
    year: "2024",
    size: [3024, 4032],
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAKAAoDASIAAhEBAxEB/8QAFAABAAAAAAAAAAAAAAAAAAAABf/EACUQAAECBQIHAQAAAAAAAAAAAAECAwAEBQYREiETIiMyQVORof/EABQBAQAAAAAAAAAAAAAAAAAAAAT/xAAXEQEBAQEAAAAAAAAAAAAAAAABABEh/9oADAMBAAIRAxEAPwAtNt0p2g1CedcTxA23oJONxgqH7iDZmSlBMuhtWUBZ0nHjMDUDqWfcC3OdWWN1bnvgMuuexf0wREzsoB2//9k=",
  },
  {
    src: `${PATH_PHOTOGRAPHY_IMAGES}/Charlestown-12-15-24.jpg`,
    alt: "A picture of the Charlestown Navy Yard in Boston, United States.",
    location: "Boston, United States",
    year: "2024",
    size: [3024, 4032],
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAKAAoDASIAAhEBAxEB/8QAFAABAAAAAAAAAAAAAAAAAAAABf/EACUQAAECBQIHAQAAAAAAAAAAAAECAwAEBQYREiETIiMyQVORof/EABQBAQAAAAAAAAAAAAAAAAAAAAT/xAAXEQEBAQEAAAAAAAAAAAAAAAABABEh/9oADAMBAAIRAxEAPwAtNt0p2g1CedcTxA23oJONxgqH7iDZmSlBMuhtWUBZ0nHjMDUDqWfcC3OdWWN1bnvgMuuexf0wREzsoB2//9k=",
  },
  {
    src: `${PATH_PHOTOGRAPHY_IMAGES}/Church-9-8-24.jpg`,
    alt: "A picture of a church field in Waterloo, Canada.",
    location: "Waterloo, Canada",
    year: "2024",
    size: [3024, 4032],
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAKAAoDASIAAhEBAxEB/8QAFAABAAAAAAAAAAAAAAAAAAAABf/EACUQAAECBQIHAQAAAAAAAAAAAAECAwAEBQYREiETIiMyQVORof/EABQBAQAAAAAAAAAAAAAAAAAAAAT/xAAXEQEBAQEAAAAAAAAAAAAAAAABABEh/9oADAMBAAIRAxEAPwAtNt0p2g1CedcTxA23oJONxgqH7iDZmSlBMuhtWUBZ0nHjMDUDqWfcC3OdWWN1bnvgMuuexf0wREzsoB2//9k=",
  },
  {
    src: `${PATH_PHOTOGRAPHY_IMAGES}/Citadel-3-22-25.jpg`,
    alt: "A picture of a Notre Dame in Montreal, Canada.",
    location: "Montreal, Canada",
    year: "2025",
    size: [3024, 4032],
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAKAAoDASIAAhEBAxEB/8QAFAABAAAAAAAAAAAAAAAAAAAABf/EACUQAAECBQIHAQAAAAAAAAAAAAECAwAEBQYREiETIiMyQVORof/EABQBAQAAAAAAAAAAAAAAAAAAAAT/xAAXEQEBAQEAAAAAAAAAAAAAAAABABEh/9oADAMBAAIRAxEAPwAtNt0p2g1CedcTxA23oJONxgqH7iDZmSlBMuhtWUBZ0nHjMDUDqWfcC3OdWWN1bnvgMuuexf0wREzsoB2//9k=",
  },
  {
    src: `${PATH_PHOTOGRAPHY_IMAGES}/ClockTower-6-21-24.jpg`,
    alt: "A picture of a clock tower in Montreal, Canada.",
    location: "Montreal, Canada",
    year: "2024",
    size: [3024, 4032],
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAKAAoDASIAAhEBAxEB/8QAFAABAAAAAAAAAAAAAAAAAAAABf/EACUQAAECBQIHAQAAAAAAAAAAAAECAwAEBQYREiETIiMyQVORof/EABQBAQAAAAAAAAAAAAAAAAAAAAT/xAAXEQEBAQEAAAAAAAAAAAAAAAABABEh/9oADAMBAAIRAxEAPwAtNt0p2g1CedcTxA23oJONxgqH7iDZmSlBMuhtWUBZ0nHjMDUDqWfcC3OdWWN1bnvgMuuexf0wREzsoB2//9k=",
  },
  {
    src: `${PATH_PHOTOGRAPHY_IMAGES}/Constitution-12-15-24.jpg`,
    alt: "A picture of the USS Constitution in Boston, United States.",
    location: "Boston, United States",
    year: "2024",
    size: [3024, 4032],
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAKAAoDASIAAhEBAxEB/8QAFAABAAAAAAAAAAAAAAAAAAAABf/EACUQAAECBQIHAQAAAAAAAAAAAAECAwAEBQYREiETIiMyQVORof/EABQBAQAAAAAAAAAAAAAAAAAAAAT/xAAXEQEBAQEAAAAAAAAAAAAAAAABABEh/9oADAMBAAIRAxEAPwAtNt0p2g1CedcTxA23oJONxgqH7iDZmSlBMuhtWUBZ0nHjMDUDqWfcC3OdWWN1bnvgMuuexf0wREzsoB2//9k=",
  },
  {
    src: `${PATH_PHOTOGRAPHY_IMAGES}/DP-10-22-24.jpg`,
    alt: "A picture of a DP in Waterloo, Canada.",
    location: "Waterloo, Canada",
    year: "2024",
    size: [4032, 3024],
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAKAAoDASIAAhEBAxEB/8QAFAABAAAAAAAAAAAAAAAAAAAABf/EACUQAAECBQIHAQAAAAAAAAAAAAECAwAEBQYREiETIiMyQVORof/EABQBAQAAAAAAAAAAAAAAAAAAAAT/xAAXEQEBAQEAAAAAAAAAAAAAAAABABEh/9oADAMBAAIRAxEAPwAtNt0p2g1CedcTxA23oJONxgqH7iDZmSlBMuhtWUBZ0nHjMDUDqWfcC3OdWWN1bnvgMuuexf0wREzsoB2//9k=",
  },
  {
    src: `${PATH_PHOTOGRAPHY_IMAGES}/Echo-5-2-24.jpg`,
    alt: "A picture of a Dog in Niagara, Canada.",
    location: "Niagara, Canada",
    year: "2024",
    size: [2496, 2343],
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAKAAoDASIAAhEBAxEB/8QAFAABAAAAAAAAAAAAAAAAAAAABf/EACUQAAECBQIHAQAAAAAAAAAAAAECAwAEBQYREiETIiMyQVORof/EABQBAQAAAAAAAAAAAAAAAAAAAAT/xAAXEQEBAQEAAAAAAAAAAAAAAAABABEh/9oADAMBAAIRAxEAPwAtNt0p2g1CedcTxA23oJONxgqH7iDZmSlBMuhtWUBZ0nHjMDUDqWfcC3OdWWN1bnvgMuuexf0wREzsoB2//9k=",
  },
  {
    src: `${PATH_PHOTOGRAPHY_IMAGES}/Frederiksborg-10-15-24.jpg`,
    alt: "A picture of Frederiksborg Castle in Hillerød, Denmark.",
    location: "Hillerød, Denmark",
    year: "2024",
    size: [3024, 4032],
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAKAAoDASIAAhEBAxEB/8QAFAABAAAAAAAAAAAAAAAAAAAABf/EACUQAAECBQIHAQAAAAAAAAAAAAECAwAEBQYREiETIiMyQVORof/EABQBAQAAAAAAAAAAAAAAAAAAAAT/xAAXEQEBAQEAAAAAAAAAAAAAAAABABEh/9oADAMBAAIRAxEAPwAtNt0p2g1CedcTxA23oJONxgqH7iDZmSlBMuhtWUBZ0nHjMDUDqWfcC3OdWWN1bnvgMuuexf0wREzsoB2//9k=",
  },
  {
    src: `${PATH_PHOTOGRAPHY_IMAGES}/Geodesic-3-22-25.jpg`,
    alt: "A picture of a the Biodome in Montreal, Canada.",
    location: "Montreal, Canada",
    year: "2025",
    size: [3024, 4032],
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAKAAoDASIAAhEBAxEB/8QAFAABAAAAAAAAAAAAAAAAAAAABf/EACUQAAECBQIHAQAAAAAAAAAAAAECAwAEBQYREiETIiMyQVORof/EABQBAQAAAAAAAAAAAAAAAAAAAAT/xAAXEQEBAQEAAAAAAAAAAAAAAAABABEh/9oADAMBAAIRAxEAPwAtNt0p2g1CedcTxA23oJONxgqH7iDZmSlBMuhtWUBZ0nHjMDUDqWfcC3OdWWN1bnvgMuuexf0wREzsoB2//9k=",
  },
  {
    src: `${PATH_PHOTOGRAPHY_IMAGES}/George-12-14-24.jpg`,
    alt: "A picture of a statue of George Washington in Boston, United States.",
    location: "Boston, United States",
    year: "2024",
    size: [3024, 4032],
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAKAAoDASIAAhEBAxEB/8QAFAABAAAAAAAAAAAAAAAAAAAABf/EACUQAAECBQIHAQAAAAAAAAAAAAECAwAEBQYREiETIiMyQVORof/EABQBAQAAAAAAAAAAAAAAAAAAAAT/xAAXEQEBAQEAAAAAAAAAAAAAAAABABEh/9oADAMBAAIRAxEAPwAtNt0p2g1CedcTxA23oJONxgqH7iDZmSlBMuhtWUBZ0nHjMDUDqWfcC3OdWWN1bnvgMuuexf0wREzsoB2//9k=",
  },
  {
    src: `${PATH_PHOTOGRAPHY_IMAGES}/GrandRiver-10-27-24.jpg`,
    alt: "A picture of the Grand River in Waterloo, Canada.",
    location: "Waterloo, Canada",
    year: "2024",
    size: [4032, 3024],
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAKAAoDASIAAhEBAxEB/8QAFAABAAAAAAAAAAAAAAAAAAAABf/EACUQAAECBQIHAQAAAAAAAAAAAAECAwAEBQYREiETIiMyQVORof/EABQBAQAAAAAAAAAAAAAAAAAAAAT/xAAXEQEBAQEAAAAAAAAAAAAAAAABABEh/9oADAMBAAIRAxEAPwAtNt0p2g1CedcTxA23oJONxgqH7iDZmSlBMuhtWUBZ0nHjMDUDqWfcC3OdWWN1bnvgMuuexf0wREzsoB2//9k=",
  },
  {
    src: `${PATH_PHOTOGRAPHY_IMAGES}/GrandRoue-2-12-25.jpg`,
    alt: "A picture of the Grand Roue in Montreal, Canada.",
    location: "Montreal, Canada",
    year: "2025",
    size: [3024, 4032],
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAKAAoDASIAAhEBAxEB/8QAFAABAAAAAAAAAAAAAAAAAAAABf/EACUQAAECBQIHAQAAAAAAAAAAAAECAwAEBQYREiETIiMyQVORof/EABQBAQAAAAAAAAAAAAAAAAAAAAT/xAAXEQEBAQEAAAAAAAAAAAAAAAABABEh/9oADAMBAAIRAxEAPwAtNt0p2g1CedcTxA23oJONxgqH7iDZmSlBMuhtWUBZ0nHjMDUDqWfcC3OdWWN1bnvgMuuexf0wREzsoB2//9k=",
  },
  {
    src: `${PATH_PHOTOGRAPHY_IMAGES}/Grundtvig-10-15-24.jpg`,
    alt: "A picture of a statue of the Grundtvig Church in Copenhagen, Denmark.",
    location: "Copenhagen, Denmark",
    year: "2024",
    size: [3024, 4032],
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAKAAoDASIAAhEBAxEB/8QAFAABAAAAAAAAAAAAAAAAAAAABf/EACUQAAECBQIHAQAAAAAAAAAAAAECAwAEBQYREiETIiMyQVORof/EABQBAQAAAAAAAAAAAAAAAAAAAAT/xAAXEQEBAQEAAAAAAAAAAAAAAAABABEh/9oADAMBAAIRAxEAPwAtNt0p2g1CedcTxA23oJONxgqH7iDZmSlBMuhtWUBZ0nHjMDUDqWfcC3OdWWN1bnvgMuuexf0wREzsoB2//9k=",
  },
  {
    src: `${PATH_PHOTOGRAPHY_IMAGES}/Hedge-10-17-24.jpg`,
    alt: "A picture of a statue of the Hedge in Copenhagen, Denmark.",
    location: "Copenhagen, Denmark",
    year: "2024",
    size: [3024, 4032],
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAKAAoDASIAAhEBAxEB/8QAFAABAAAAAAAAAAAAAAAAAAAABf/EACUQAAECBQIHAQAAAAAAAAAAAAECAwAEBQYREiETIiMyQVORof/EABQBAQAAAAAAAAAAAAAAAAAAAAT/xAAXEQEBAQEAAAAAAAAAAAAAAAABABEh/9oADAMBAAIRAxEAPwAtNt0p2g1CedcTxA23oJONxgqH7iDZmSlBMuhtWUBZ0nHjMDUDqWfcC3OdWWN1bnvgMuuexf0wREzsoB2//9k=",
  },
  {
    src: `${PATH_PHOTOGRAPHY_IMAGES}/IsabellaStewart-12-16-24.jpg`,
    alt: "A picture of a statue of the Isabella Stewart Gardner Museum in Boston, United States.",
    location: "Boston, United States",
    year: "2024",
    size: [3024, 4032],
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAKAAoDASIAAhEBAxEB/8QAFAABAAAAAAAAAAAAAAAAAAAABf/EACUQAAECBQIHAQAAAAAAAAAAAAECAwAEBQYREiETIiMyQVORof/EABQBAQAAAAAAAAAAAAAAAAAAAAT/xAAXEQEBAQEAAAAAAAAAAAAAAAABABEh/9oADAMBAAIRAxEAPwAtNt0p2g1CedcTxA23oJONxgqH7iDZmSlBMuhtWUBZ0nHjMDUDqWfcC3OdWWN1bnvgMuuexf0wREzsoB2//9k=",
  },
  {
    src: `${PATH_PHOTOGRAPHY_IMAGES}/Ladybug-10-18-24.jpg`,
    alt: "A picture of a Ladybug in Copenhagen, Denmark.",
    location: "Copenhagen, Denmark",
    year: "2024",
    size: [3024, 4032],
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAKAAoDASIAAhEBAxEB/8QAFAABAAAAAAAAAAAAAAAAAAAABf/EACUQAAECBQIHAQAAAAAAAAAAAAECAwAEBQYREiETIiMyQVORof/EABQBAQAAAAAAAAAAAAAAAAAAAAT/xAAXEQEBAQEAAAAAAAAAAAAAAAABABEh/9oADAMBAAIRAxEAPwAtNt0p2g1CedcTxA23oJONxgqH7iDZmSlBMuhtWUBZ0nHjMDUDqWfcC3OdWWN1bnvgMuuexf0wREzsoB2//9k=",
  },
  {
    src: `${PATH_PHOTOGRAPHY_IMAGES}/Lighthouse-4-20-25.jpg`,
    alt: "A picture of a lighthouse in Oakville, Canada.",
    location: "Oakville, Canada",
    year: "2024",
    size: [3024, 4032],
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAKAAoDASIAAhEBAxEB/8QAFAABAAAAAAAAAAAAAAAAAAAABf/EACUQAAECBQIHAQAAAAAAAAAAAAECAwAEBQYREiETIiMyQVORof/EABQBAQAAAAAAAAAAAAAAAAAAAAT/xAAXEQEBAQEAAAAAAAAAAAAAAAABABEh/9oADAMBAAIRAxEAPwAtNt0p2g1CedcTxA23oJONxgqH7iDZmSlBMuhtWUBZ0nHjMDUDqWfcC3OdWWN1bnvgMuuexf0wREzsoB2//9k=",
  },
  {
    src: `${PATH_PHOTOGRAPHY_IMAGES}/Marineland-8-28-24.jpg`,
    alt: "A picture of Marineland in Niagara Falls, Canada.",
    location: "Niagara Falls, Canada",
    year: "2024",
    size: [3024, 4032],
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAKAAoDASIAAhEBAxEB/8QAFAABAAAAAAAAAAAAAAAAAAAABf/EACUQAAECBQIHAQAAAAAAAAAAAAECAwAEBQYREiETIiMyQVORof/EABQBAQAAAAAAAAAAAAAAAAAAAAT/xAAXEQEBAQEAAAAAAAAAAAAAAAABABEh/9oADAMBAAIRAxEAPwAtNt0p2g1CedcTxA23oJONxgqH7iDZmSlBMuhtWUBZ0nHjMDUDqWfcC3OdWWN1bnvgMuuexf0wREzsoB2//9k=",
  },
  {
    src: `${PATH_PHOTOGRAPHY_IMAGES}/Metro-10-17-25.jpg`,
    alt: "A picture of the metro in Copenhagen, Denmark.",
    location: "Copenhagen, Denmark",
    year: "2024",
    size: [3024, 4032],
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAKAAoDASIAAhEBAxEB/8QAFAABAAAAAAAAAAAAAAAAAAAABf/EACUQAAECBQIHAQAAAAAAAAAAAAECAwAEBQYREiETIiMyQVORof/EABQBAQAAAAAAAAAAAAAAAAAAAAT/xAAXEQEBAQEAAAAAAAAAAAAAAAABABEh/9oADAMBAAIRAxEAPwAtNt0p2g1CedcTxA23oJONxgqH7iDZmSlBMuhtWUBZ0nHjMDUDqWfcC3OdWWN1bnvgMuuexf0wREzsoB2//9k=",
  },
  {
    src: `${PATH_PHOTOGRAPHY_IMAGES}/Murder-1-16-25.jpg`,
    alt: "A picture of a lamppost in Montreal, Canada.",
    location: "Montreal, Canada",
    year: "2025",
    size: [3024, 4032],
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAKAAoDASIAAhEBAxEB/8QAFAABAAAAAAAAAAAAAAAAAAAABf/EACUQAAECBQIHAQAAAAAAAAAAAAECAwAEBQYREiETIiMyQVORof/EABQBAQAAAAAAAAAAAAAAAAAAAAT/xAAXEQEBAQEAAAAAAAAAAAAAAAABABEh/9oADAMBAAIRAxEAPwAtNt0p2g1CedcTxA23oJONxgqH7iDZmSlBMuhtWUBZ0nHjMDUDqWfcC3OdWWN1bnvgMuuexf0wREzsoB2//9k=",
  },
  {
    src: `${PATH_PHOTOGRAPHY_IMAGES}/NotreDame-1-4-25.jpg`,
    alt: "A picture of a Notre Dame in Montreal, Canada.",
    location: "Montreal, Canada",
    year: "2025",
    size: [3024, 4032],
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAKAAoDASIAAhEBAxEB/8QAFAABAAAAAAAAAAAAAAAAAAAABf/EACUQAAECBQIHAQAAAAAAAAAAAAECAwAEBQYREiETIiMyQVORof/EABQBAQAAAAAAAAAAAAAAAAAAAAT/xAAXEQEBAQEAAAAAAAAAAAAAAAABABEh/9oADAMBAAIRAxEAPwAtNt0p2g1CedcTxA23oJONxgqH7iDZmSlBMuhtWUBZ0nHjMDUDqWfcC3OdWWN1bnvgMuuexf0wREzsoB2//9k=",
  },
  {
    src: `${PATH_PHOTOGRAPHY_IMAGES}/Pier-10-18-24.jpg`,
    alt: "A picture of a pier in Malmo, Sweden.",
    location: "Malmo, Sweden",
    year: "2024",
    size: [4032, 3024],
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAKAAoDASIAAhEBAxEB/8QAFAABAAAAAAAAAAAAAAAAAAAABf/EACUQAAECBQIHAQAAAAAAAAAAAAECAwAEBQYREiETIiMyQVORof/EABQBAQAAAAAAAAAAAAAAAAAAAAT/xAAXEQEBAQEAAAAAAAAAAAAAAAABABEh/9oADAMBAAIRAxEAPwAtNt0p2g1CedcTxA23oJONxgqH7iDZmSlBMuhtWUBZ0nHjMDUDqWfcC3OdWWN1bnvgMuuexf0wREzsoB2//9k=",
  },
  {
    src: `${PATH_PHOTOGRAPHY_IMAGES}/PlantWall-5-12-24.jpg`,
    alt: "A picture of a plant wall in Waterloo, Canada.",
    location: "Waterloo, Canada",
    year: "2024",
    size: [3024, 4032],
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAKAAoDASIAAhEBAxEB/8QAFAABAAAAAAAAAAAAAAAAAAAABf/EACUQAAECBQIHAQAAAAAAAAAAAAECAwAEBQYREiETIiMyQVORof/EABQBAQAAAAAAAAAAAAAAAAAAAAT/xAAXEQEBAQEAAAAAAAAAAAAAAAABABEh/9oADAMBAAIRAxEAPwAtNt0p2g1CedcTxA23oJONxgqH7iDZmSlBMuhtWUBZ0nHjMDUDqWfcC3OdWWN1bnvgMuuexf0wREzsoB2//9k=",
  },
  {
    src: `${PATH_PHOTOGRAPHY_IMAGES}/Pot-4-26-24.jpg`,
    alt: "A picture of a pot in Niagara, Canada.",
    location: "Niagara, Canada",
    year: "2024",
    size: [3024, 4032],
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAKAAoDASIAAhEBAxEB/8QAFAABAAAAAAAAAAAAAAAAAAAABf/EACUQAAECBQIHAQAAAAAAAAAAAAECAwAEBQYREiETIiMyQVORof/EABQBAQAAAAAAAAAAAAAAAAAAAAT/xAAXEQEBAQEAAAAAAAAAAAAAAAABABEh/9oADAMBAAIRAxEAPwAtNt0p2g1CedcTxA23oJONxgqH7iDZmSlBMuhtWUBZ0nHjMDUDqWfcC3OdWWN1bnvgMuuexf0wREzsoB2//9k=",
  },
  {
    src: `${PATH_PHOTOGRAPHY_IMAGES}/Rezone-10-22-24.jpg`,
    alt: "A picture of Rezone in Waterloo, Canada.",
    location: "Waterloo, Canada",
    year: "2024",
    size: [3024, 4032],
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAKAAoDASIAAhEBAxEB/8QAFAABAAAAAAAAAAAAAAAAAAAABf/EACUQAAECBQIHAQAAAAAAAAAAAAECAwAEBQYREiETIiMyQVORof/EABQBAQAAAAAAAAAAAAAAAAAAAAT/xAAXEQEBAQEAAAAAAAAAAAAAAAABABEh/9oADAMBAAIRAxEAPwAtNt0p2g1CedcTxA23oJONxgqH7iDZmSlBMuhtWUBZ0nHjMDUDqWfcC3OdWWN1bnvgMuuexf0wREzsoB2//9k=",
  },
  {
    src: `${PATH_PHOTOGRAPHY_IMAGES}/Ring-6-15-24.jpg`,
    alt: "A picture of a big Ring in Montreal, Canada.",
    location: "Montreal, Canada",
    year: "2024",
    size: [3024, 4032],
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAKAAoDASIAAhEBAxEB/8QAFAABAAAAAAAAAAAAAAAAAAAABf/EACUQAAECBQIHAQAAAAAAAAAAAAECAwAEBQYREiETIiMyQVORof/EABQBAQAAAAAAAAAAAAAAAAAAAAT/xAAXEQEBAQEAAAAAAAAAAAAAAAABABEh/9oADAMBAAIRAxEAPwAtNt0p2g1CedcTxA23oJONxgqH7iDZmSlBMuhtWUBZ0nHjMDUDqWfcC3OdWWN1bnvgMuuexf0wREzsoB2//9k=",
  },
  {
    src: `${PATH_PHOTOGRAPHY_IMAGES}/Shoreline-10-15-24.jpg`,
    alt: "A picture of a shoreline in Copenhagen, Denmark.",
    location: "Copenhagen, Denmark",
    year: "2024",
    size: [4032, 3024],
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAKAAoDASIAAhEBAxEB/8QAFAABAAAAAAAAAAAAAAAAAAAABf/EACUQAAECBQIHAQAAAAAAAAAAAAECAwAEBQYREiETIiMyQVORof/EABQBAQAAAAAAAAAAAAAAAAAAAAT/xAAXEQEBAQEAAAAAAAAAAAAAAAABABEh/9oADAMBAAIRAxEAPwAtNt0p2g1CedcTxA23oJONxgqH7iDZmSlBMuhtWUBZ0nHjMDUDqWfcC3OdWWN1bnvgMuuexf0wREzsoB2//9k=",
  },
  {
    src: `${PATH_PHOTOGRAPHY_IMAGES}/Shoreline2-10-15-24.jpg`,
    alt: "A picture of a shoreline in Copenhagen, Denmark.",
    location: "Copenhagen, Denmark",
    year: "2024",
    size: [3024, 4032],
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAKAAoDASIAAhEBAxEB/8QAFAABAAAAAAAAAAAAAAAAAAAABf/EACUQAAECBQIHAQAAAAAAAAAAAAECAwAEBQYREiETIiMyQVORof/EABQBAQAAAAAAAAAAAAAAAAAAAAT/xAAXEQEBAQEAAAAAAAAAAAAAAAABABEh/9oADAMBAAIRAxEAPwAtNt0p2g1CedcTxA23oJONxgqH7iDZmSlBMuhtWUBZ0nHjMDUDqWfcC3OdWWN1bnvgMuuexf0wREzsoB2//9k=",
  },
  {
    src: `${PATH_PHOTOGRAPHY_IMAGES}/Split-4-22-24.jpg`,
    alt: "A picture of a sunset in Waterloo, Canada.",
    location: "Waterloo, Canada",
    year: "2024",
    size: [3024, 4032],
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAKAAoDASIAAhEBAxEB/8QAFAABAAAAAAAAAAAAAAAAAAAABf/EACUQAAECBQIHAQAAAAAAAAAAAAECAwAEBQYREiETIiMyQVORof/EABQBAQAAAAAAAAAAAAAAAAAAAAT/xAAXEQEBAQEAAAAAAAAAAAAAAAABABEh/9oADAMBAAIRAxEAPwAtNt0p2g1CedcTxA23oJONxgqH7iDZmSlBMuhtWUBZ0nHjMDUDqWfcC3OdWWN1bnvgMuuexf0wREzsoB2//9k=",
  },
  {
    src: `${PATH_PHOTOGRAPHY_IMAGES}/StLaurent-4-12-25.jpg`,
    alt: "A picture of the St. Laurent in Quebec City, Canada.",
    location: "Quebec City, Canada",
    year: "2025",
    size: [4032, 3024],
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAKAAoDASIAAhEBAxEB/8QAFAABAAAAAAAAAAAAAAAAAAAABf/EACUQAAECBQIHAQAAAAAAAAAAAAECAwAEBQYREiETIiMyQVORof/EABQBAQAAAAAAAAAAAAAAAAAAAAT/xAAXEQEBAQEAAAAAAAAAAAAAAAABABEh/9oADAMBAAIRAxEAPwAtNt0p2g1CedcTxA23oJONxgqH7iDZmSlBMuhtWUBZ0nHjMDUDqWfcC3OdWWN1bnvgMuuexf0wREzsoB2//9k=",
  },
  {
    src: `${PATH_PHOTOGRAPHY_IMAGES}/Theater-12-14-24.jpg`,
    alt: "A picture of a theatre in Boston, United States.",
    location: "Boston, United States",
    year: "2024",
    size: [3024, 4032],
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAKAAoDASIAAhEBAxEB/8QAFAABAAAAAAAAAAAAAAAAAAAABf/EACUQAAECBQIHAQAAAAAAAAAAAAECAwAEBQYREiETIiMyQVORof/EABQBAQAAAAAAAAAAAAAAAAAAAAT/xAAXEQEBAQEAAAAAAAAAAAAAAAABABEh/9oADAMBAAIRAxEAPwAtNt0p2g1CedcTxA23oJONxgqH7iDZmSlBMuhtWUBZ0nHjMDUDqWfcC3OdWWN1bnvgMuuexf0wREzsoB2//9k=",
  },
  {
    src: `${PATH_PHOTOGRAPHY_IMAGES}/TheDemon-10-16-24.jpg`,
    alt: "A picture of the Demon in Copenhagen, Denmark.",
    location: "Copenhagen, Denmark",
    year: "2024",
    size: [3024, 4032],
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAKAAoDASIAAhEBAxEB/8QAFAABAAAAAAAAAAAAAAAAAAAABf/EACUQAAECBQIHAQAAAAAAAAAAAAECAwAEBQYREiETIiMyQVORof/EABQBAQAAAAAAAAAAAAAAAAAAAAT/xAAXEQEBAQEAAAAAAAAAAAAAAAABABEh/9oADAMBAAIRAxEAPwAtNt0p2g1CedcTxA23oJONxgqH7iDZmSlBMuhtWUBZ0nHjMDUDqWfcC3OdWWN1bnvgMuuexf0wREzsoB2//9k=",
  },
  {
    src: `${PATH_PHOTOGRAPHY_IMAGES}/Toronto-8-24-24.jpg`,
    alt: "A picture of Toronto, Canada.",
    location: "Toronto, Canada",
    year: "2024",
    size: [3024, 4032],
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAKAAoDASIAAhEBAxEB/8QAFAABAAAAAAAAAAAAAAAAAAAABf/EACUQAAECBQIHAQAAAAAAAAAAAAECAwAEBQYREiETIiMyQVORof/EABQBAQAAAAAAAAAAAAAAAAAAAAT/xAAXEQEBAQEAAAAAAAAAAAAAAAABABEh/9oADAMBAAIRAxEAPwAtNt0p2g1CedcTxA23oJONxgqH7iDZmSlBMuhtWUBZ0nHjMDUDqWfcC3OdWWN1bnvgMuuexf0wREzsoB2//9k=",
  },
  {
    src: `${PATH_PHOTOGRAPHY_IMAGES}/Tower-10-14-24.jpg`,
    alt: "A picture of a rotating tower in Copenhagen, Denmark.",
    location: "Copenhagen, Denmark",
    year: "2024",
    size: [3024, 4032],
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAKAAoDASIAAhEBAxEB/8QAFAABAAAAAAAAAAAAAAAAAAAABf/EACUQAAECBQIHAQAAAAAAAAAAAAECAwAEBQYREiETIiMyQVORof/EABQBAQAAAAAAAAAAAAAAAAAAAAT/xAAXEQEBAQEAAAAAAAAAAAAAAAABABEh/9oADAMBAAIRAxEAPwAtNt0p2g1CedcTxA23oJONxgqH7iDZmSlBMuhtWUBZ0nHjMDUDqWfcC3OdWWN1bnvgMuuexf0wREzsoB2//9k=",
  },
  {
    src: `${PATH_PHOTOGRAPHY_IMAGES}/ToysRUs-5-18-24.jpg`,
    alt: "A picture of the Toys R Us in St. Catharines, Canada.",
    location: "St. Catharines, Canada",
    year: "2024",
    size: [3024, 3615],
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAKAAoDASIAAhEBAxEB/8QAFAABAAAAAAAAAAAAAAAAAAAABf/EACUQAAECBQIHAQAAAAAAAAAAAAECAwAEBQYREiETIiMyQVORof/EABQBAQAAAAAAAAAAAAAAAAAAAAT/xAAXEQEBAQEAAAAAAAAAAAAAAAABABEh/9oADAMBAAIRAxEAPwAtNt0p2g1CedcTxA23oJONxgqH7iDZmSlBMuhtWUBZ0nHjMDUDqWfcC3OdWWN1bnvgMuuexf0wREzsoB2//9k=",
  },
  {
    src: `${PATH_PHOTOGRAPHY_IMAGES}/Trees-4-29-24.jpg`,
    alt: "A picture of trees in Niagara, Canada.",
    location: "Niagara, Canada",
    year: "2024",
    size: [3024, 3564],
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAKAAoDASIAAhEBAxEB/8QAFAABAAAAAAAAAAAAAAAAAAAABf/EACUQAAECBQIHAQAAAAAAAAAAAAECAwAEBQYREiETIiMyQVORof/EABQBAQAAAAAAAAAAAAAAAAAAAAT/xAAXEQEBAQEAAAAAAAAAAAAAAAABABEh/9oADAMBAAIRAxEAPwAtNt0p2g1CedcTxA23oJONxgqH7iDZmSlBMuhtWUBZ0nHjMDUDqWfcC3OdWWN1bnvgMuuexf0wREzsoB2//9k=",
  },
  {
    src: `${PATH_PHOTOGRAPHY_IMAGES}/angie.jpg`,
    alt: "A picture of Angie in Ottawa, Canada.",
    location: "Ottawa, Canada",
    year: "2026",
    size: [3072, 4080],
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAKAAoDASIAAhEBAxEB/8QAFAABAAAAAAAAAAAAAAAAAAAABf/EACUQAAECBQIHAQAAAAAAAAAAAAECAwAEBQYREiETIiMyQVORof/EABQBAQAAAAAAAAAAAAAAAAAAAAT/xAAXEQEBAQEAAAAAAAAAAAAAAAABABEh/9oADAMBAAIRAxEAPwAtNt0p2g1CedcTxA23oJONxgqH7iDZmSlBMuhtWUBZ0nHjMDUDqWfcC3OdWWN1bnvgMuuexf0wREzsoB2//9k=",
  },
  {
    src: `${PATH_PHOTOGRAPHY_IMAGES}/ballsfalls.jpg`,
    alt: "A picture of the Balls Falls in Canada.",
    location: "Ball's Falls, Canada",
    year: "2025",
    size: [6144, 8160],
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAKAAoDASIAAhEBAxEB/8QAFAABAAAAAAAAAAAAAAAAAAAABf/EACUQAAECBQIHAQAAAAAAAAAAAAECAwAEBQYREiETIiMyQVORof/EABQBAQAAAAAAAAAAAAAAAAAAAAT/xAAXEQEBAQEAAAAAAAAAAAAAAAABABEh/9oADAMBAAIRAxEAPwAtNt0p2g1CedcTxA23oJONxgqH7iDZmSlBMuhtWUBZ0nHjMDUDqWfcC3OdWWN1bnvgMuuexf0wREzsoB2//9k=",
  },
  {
    src: `${PATH_PHOTOGRAPHY_IMAGES}/flowers.jpg`,
    alt: "A picture of the Flowers in Waterloo, Canada.",
    location: "Waterloo, Canada",
    year: "2025",
    size: [3072, 4080],
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAKAAoDASIAAhEBAxEB/8QAFAABAAAAAAAAAAAAAAAAAAAABf/EACUQAAECBQIHAQAAAAAAAAAAAAECAwAEBQYREiETIiMyQVORof/EABQBAQAAAAAAAAAAAAAAAAAAAAT/xAAXEQEBAQEAAAAAAAAAAAAAAAABABEh/9oADAMBAAIRAxEAPwAtNt0p2g1CedcTxA23oJONxgqH7iDZmSlBMuhtWUBZ0nHjMDUDqWfcC3OdWWN1bnvgMuuexf0wREzsoB2//9k=",
  },
  {
    src: `${PATH_PHOTOGRAPHY_IMAGES}/garden.jpg`,
    alt: "A picture of the Botanical Garden in Montreal, Canada.",
    location: "Montreal, Canada",
    year: "2025",
    size: [6144, 8160],
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAKAAoDASIAAhEBAxEB/8QAFAABAAAAAAAAAAAAAAAAAAAABf/EACUQAAECBQIHAQAAAAAAAAAAAAECAwAEBQYREiETIiMyQVORof/EABQBAQAAAAAAAAAAAAAAAAAAAAT/xAAXEQEBAQEAAAAAAAAAAAAAAAABABEh/9oADAMBAAIRAxEAPwAtNt0p2g1CedcTxA23oJONxgqH7iDZmSlBMuhtWUBZ0nHjMDUDqWfcC3OdWWN1bnvgMuuexf0wREzsoB2//9k=",
  },
  {
    src: `${PATH_PHOTOGRAPHY_IMAGES}/goldenhour.jpg`,
    alt: "A picture of the train station in Burlington, Canada.",
    location: "Burlington, Canada",
    year: "2025",
    size: [3072, 4080],
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAKAAoDASIAAhEBAxEB/8QAFAABAAAAAAAAAAAAAAAAAAAABf/EACUQAAECBQIHAQAAAAAAAAAAAAECAwAEBQYREiETIiMyQVORof/EABQBAQAAAAAAAAAAAAAAAAAAAAT/xAAXEQEBAQEAAAAAAAAAAAAAAAABABEh/9oADAMBAAIRAxEAPwAtNt0p2g1CedcTxA23oJONxgqH7iDZmSlBMuhtWUBZ0nHjMDUDqWfcC3OdWWN1bnvgMuuexf0wREzsoB2//9k=",
  },
  {
    src: `${PATH_PHOTOGRAPHY_IMAGES}/icon.jpg`,
    alt: "A picture of the ICON in Waterloo, Canada.",
    location: "Waterloo, Canada",
    year: "2025",
    size: [3072, 4080],
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAKAAoDASIAAhEBAxEB/8QAFAABAAAAAAAAAAAAAAAAAAAABf/EACUQAAECBQIHAQAAAAAAAAAAAAECAwAEBQYREiETIiMyQVORof/EABQBAQAAAAAAAAAAAAAAAAAAAAT/xAAXEQEBAQEAAAAAAAAAAAAAAAABABEh/9oADAMBAAIRAxEAPwAtNt0p2g1CedcTxA23oJONxgqH7iDZmSlBMuhtWUBZ0nHjMDUDqWfcC3OdWWN1bnvgMuuexf0wREzsoB2//9k=",
  },
  {
    src: `${PATH_PHOTOGRAPHY_IMAGES}/islands.jpg`,
    alt: "A picture of Toronto, Canada.",
    location: "Toronto, Canada",
    year: "2025",
    size: [4080, 3072],
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAKAAoDASIAAhEBAxEB/8QAFAABAAAAAAAAAAAAAAAAAAAABf/EACUQAAECBQIHAQAAAAAAAAAAAAECAwAEBQYREiETIiMyQVORof/EABQBAQAAAAAAAAAAAAAAAAAAAAT/xAAXEQEBAQEAAAAAAAAAAAAAAAABABEh/9oADAMBAAIRAxEAPwAtNt0p2g1CedcTxA23oJONxgqH7iDZmSlBMuhtWUBZ0nHjMDUDqWfcC3OdWWN1bnvgMuuexf0wREzsoB2//9k=",
  },
  {
    src: `${PATH_PHOTOGRAPHY_IMAGES}/lake.jpg`,
    alt: "A picture of the lake in Quebec, Canada.",
    location: "Quebec, Canada",
    year: "2025",
    size: [3072, 4080],
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAKAAoDASIAAhEBAxEB/8QAFAABAAAAAAAAAAAAAAAAAAAABf/EACUQAAECBQIHAQAAAAAAAAAAAAECAwAEBQYREiETIiMyQVORof/EABQBAQAAAAAAAAAAAAAAAAAAAAT/xAAXEQEBAQEAAAAAAAAAAAAAAAABABEh/9oADAMBAAIRAxEAPwAtNt0p2g1CedcTxA23oJONxgqH7iDZmSlBMuhtWUBZ0nHjMDUDqWfcC3OdWWN1bnvgMuuexf0wREzsoB2//9k=",
  },
  {
    src: `${PATH_PHOTOGRAPHY_IMAGES}/metro.jpg`,
    alt: "A picture of the metro in Montreal, Canada.",
    location: "Montreal, Canada",
    year: "2025",
    size: [3072, 4080],
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAKAAoDASIAAhEBAxEB/8QAFAABAAAAAAAAAAAAAAAAAAAABf/EACUQAAECBQIHAQAAAAAAAAAAAAECAwAEBQYREiETIiMyQVORof/EABQBAQAAAAAAAAAAAAAAAAAAAAT/xAAXEQEBAQEAAAAAAAAAAAAAAAABABEh/9oADAMBAAIRAxEAPwAtNt0p2g1CedcTxA23oJONxgqH7iDZmSlBMuhtWUBZ0nHjMDUDqWfcC3OdWWN1bnvgMuuexf0wREzsoB2//9k=",
  },
  {
    src: `${PATH_PHOTOGRAPHY_IMAGES}/music.jpg`,
    alt: "A picture of a musician in Montreal, Canada.",
    location: "Montreal, Canada",
    year: "2025",
    size: [3072, 4080],
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAKAAoDASIAAhEBAxEB/8QAFAABAAAAAAAAAAAAAAAAAAAABf/EACUQAAECBQIHAQAAAAAAAAAAAAECAwAEBQYREiETIiMyQVORof/EABQBAQAAAAAAAAAAAAAAAAAAAAT/xAAXEQEBAQEAAAAAAAAAAAAAAAABABEh/9oADAMBAAIRAxEAPwAtNt0p2g1CedcTxA23oJONxgqH7iDZmSlBMuhtWUBZ0nHjMDUDqWfcC3OdWWN1bnvgMuuexf0wREzsoB2//9k=",
  },
  {
    src: `${PATH_PHOTOGRAPHY_IMAGES}/niagara.jpg`,
    alt: "A picture of the sky in Niagara, Canada.",
    location: "Niagara, Canada",
    year: "2025",
    size: [3072, 4080],
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAKAAoDASIAAhEBAxEB/8QAFAABAAAAAAAAAAAAAAAAAAAABf/EACUQAAECBQIHAQAAAAAAAAAAAAECAwAEBQYREiETIiMyQVORof/EABQBAQAAAAAAAAAAAAAAAAAAAAT/xAAXEQEBAQEAAAAAAAAAAAAAAAABABEh/9oADAMBAAIRAxEAPwAtNt0p2g1CedcTxA23oJONxgqH7iDZmSlBMuhtWUBZ0nHjMDUDqWfcC3OdWWN1bnvgMuuexf0wREzsoB2//9k=",
  },
  {
    src: `${PATH_PHOTOGRAPHY_IMAGES}/niagara.jpg`,
    alt: "A picture of the frozen Niagara Falls in Canada.",
    location: "Niagara Falls, Canada",
    year: "2026",
    size: [4080, 3072],
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAKAAoDASIAAhEBAxEB/8QAFAABAAAAAAAAAAAAAAAAAAAABf/EACUQAAECBQIHAQAAAAAAAAAAAAECAwAEBQYREiETIiMyQVORof/EABQBAQAAAAAAAAAAAAAAAAAAAAT/xAAXEQEBAQEAAAAAAAAAAAAAAAABABEh/9oADAMBAAIRAxEAPwAtNt0p2g1CedcTxA23oJONxgqH7iDZmSlBMuhtWUBZ0nHjMDUDqWfcC3OdWWN1bnvgMuuexf0wREzsoB2//9k=",
  },
  {
    src: `${PATH_PHOTOGRAPHY_IMAGES}/pelham.jpg`,
    alt: "A picture of uptown Pelham, Canada.",
    location: "Pelham, Canada",
    year: "2026",
    size: [2586, 3421],
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAKAAoDASIAAhEBAxEB/8QAFAABAAAAAAAAAAAAAAAAAAAABf/EACUQAAECBQIHAQAAAAAAAAAAAAECAwAEBQYREiETIiMyQVORof/EABQBAQAAAAAAAAAAAAAAAAAAAAT/xAAXEQEBAQEAAAAAAAAAAAAAAAABABEh/9oADAMBAAIRAxEAPwAtNt0p2g1CedcTxA23oJONxgqH7iDZmSlBMuhtWUBZ0nHjMDUDqWfcC3OdWWN1bnvgMuuexf0wREzsoB2//9k=",
  },
  {
    src: `${PATH_PHOTOGRAPHY_IMAGES}/sunset.jpg`,
    alt: "A picture of the Waterloo, Canada.",
    location: "Waterloo, Canada",
    year: "2025",
    size: [3072, 4080],
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAKAAoDASIAAhEBAxEB/8QAFAABAAAAAAAAAAAAAAAAAAAABf/EACUQAAECBQIHAQAAAAAAAAAAAAECAwAEBQYREiETIiMyQVORof/EABQBAQAAAAAAAAAAAAAAAAAAAAT/xAAXEQEBAQEAAAAAAAAAAAAAAAABABEh/9oADAMBAAIRAxEAPwAtNt0p2g1CedcTxA23oJONxgqH7iDZmSlBMuhtWUBZ0nHjMDUDqWfcC3OdWWN1bnvgMuuexf0wREzsoB2//9k=",
  },
  {
    src: `${PATH_PHOTOGRAPHY_IMAGES}/tower.jpg`,
    alt: "A picture of the Niagara Falls, Canada.",
    location: "Niagara Falls, Canada",
    year: "2026",
    size: [6144, 8160],
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAKAAoDASIAAhEBAxEB/8QAFAABAAAAAAAAAAAAAAAAAAAABf/EACUQAAECBQIHAQAAAAAAAAAAAAECAwAEBQYREiETIiMyQVORof/EABQBAQAAAAAAAAAAAAAAAAAAAAT/xAAXEQEBAQEAAAAAAAAAAAAAAAABABEh/9oADAMBAAIRAxEAPwAtNt0p2g1CedcTxA23oJONxgqH7iDZmSlBMuhtWUBZ0nHjMDUDqWfcC3OdWWN1bnvgMuuexf0wREzsoB2//9k=",
  },
  {
    src: `${PATH_PHOTOGRAPHY_IMAGES}/waterloo.jpg`,
    alt: "A picture of the Waterloo, Canada.",
    location: "Waterloo, Canada",
    year: "2026",
    size: [3072, 4080],
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAKAAoDASIAAhEBAxEB/8QAFAABAAAAAAAAAAAAAAAAAAAABf/EACUQAAECBQIHAQAAAAAAAAAAAAECAwAEBQYREiETIiMyQVORof/EABQBAQAAAAAAAAAAAAAAAAAAAAT/xAAXEQEBAQEAAAAAAAAAAAAAAAABABEh/9oADAMBAAIRAxEAPwAtNt0p2g1CedcTxA23oJONxgqH7iDZmSlBMuhtWUBZ0nHjMDUDqWfcC3OdWWN1bnvgMuuexf0wREzsoB2//9k=",
  },
  {
    src: `${PATH_PHOTOGRAPHY_IMAGES}/waterloopark.jpg`,
    alt: "A picture of Waterloo Park, Canada.",
    location: "Waterloo, Canada",
    year: "2026",
    size: [4080, 3072],
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAKAAoDASIAAhEBAxEB/8QAFAABAAAAAAAAAAAAAAAAAAAABf/EACUQAAECBQIHAQAAAAAAAAAAAAECAwAEBQYREiETIiMyQVORof/EABQBAQAAAAAAAAAAAAAAAAAAAAT/xAAXEQEBAQEAAAAAAAAAAAAAAAABABEh/9oADAMBAAIRAxEAPwAtNt0p2g1CedcTxA23oJONxgqH7iDZmSlBMuhtWUBZ0nHjMDUDqWfcC3OdWWN1bnvgMuuexf0wREzsoB2//9k=",
  },
  {
    src: `${PATH_PHOTOGRAPHY_IMAGES}/wonderland.jpg`,
    alt: "A picture of Vaughan, Canada.",
    location: "Vaughan, Canada",
    year: "2025",
    size: [3072, 4080],
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAKAAoDASIAAhEBAxEB/8QAFAABAAAAAAAAAAAAAAAAAAAABf/EACUQAAECBQIHAQAAAAAAAAAAAAECAwAEBQYREiETIiMyQVORof/EABQBAQAAAAAAAAAAAAAAAAAAAAT/xAAXEQEBAQEAAAAAAAAAAAAAAAABABEh/9oADAMBAAIRAxEAPwAtNt0p2g1CedcTxA23oJONxgqH7iDZmSlBMuhtWUBZ0nHjMDUDqWfcC3OdWWN1bnvgMuuexf0wREzsoB2//9k=",
  },
]