import { MasonryImage } from "@/components/common/photos/MasonryLayout";
import { PATH_PHOTOGRAPHY_IMAGES } from "@/lib/constants";

export const photos: MasonryImage[] = [
  {
    src: `${PATH_PHOTOGRAPHY_IMAGES}/Angel-3-15-25.jpg`,
    alt: "A picture of an angel statue in a park in Montreal, Canada.",
    location: "Montreal, Canada",
    year: "2025",
    size: [3024, 4032],
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAKAAoDASIAAhEBAxEB/8QAFAABAAAAAAAAAAAAAAAAAAAABf/EACUQAAECBQIHAQAAAAAAAAAAAAECAwAEBQYREiETIiMyQVORof/EABQBAQAAAAAAAAAAAAAAAAAAAAT/xAAXEQEBAQEAAAAAAAAAAAAAAAABABEh/9oADAMBAAIRAxEAPwAtNt0p2g1CedcTxA23oJONxgqH7iDZmSlBMuhtWUBZ0nHjMDUDqWfcC3OdWWN1bnvgMuuexf0wREzsoB2//9k=",
  },
  {
    src: `${PATH_PHOTOGRAPHY_IMAGES}/Athena-10-17-24.jpg`,
    alt: "A picture of an Athena statue in Copenhagen, Denmark.",
    location: "Copenhagen, Denmark",
    year: "2024",
    size: [3024, 4032],
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAKAAoDASIAAhEBAxEB/8QAFAABAAAAAAAAAAAAAAAAAAAABf/EACUQAAECBQIHAQAAAAAAAAAAAAECAwAEBQYREiETIiMyQVORof/EABQBAQAAAAAAAAAAAAAAAAAAAAT/xAAXEQEBAQEAAAAAAAAAAAAAAAABABEh/9oADAMBAAIRAxEAPwAtNt0p2g1CedcTxA23oJONxgqH7iDZmSlBMuhtWUBZ0nHjMDUDqWfcC3OdWWN1bnvgMuuexf0wREzsoB2//9k=",
  },
  {
    src: `${PATH_PHOTOGRAPHY_IMAGES}/Beluga-8-28-24.jpg`,
    alt: "A picture of a Beluga whale at Marineland in Niagara Falls, Canada.",
    location: "Niagara Falls, Canada",
    year: "2024",
    size: [3024, 4032],
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAKAAoDASIAAhEBAxEB/8QAFAABAAAAAAAAAAAAAAAAAAAABf/EACUQAAECBQIHAQAAAAAAAAAAAAECAwAEBQYREiETIiMyQVORof/EABQBAQAAAAAAAAAAAAAAAAAAAAT/xAAXEQEBAQEAAAAAAAAAAAAAAAABABEh/9oADAMBAAIRAxEAPwAtNt0p2g1CedcTxA23oJONxgqH7iDZmSlBMuhtWUBZ0nHjMDUDqWfcC3OdWWN1bnvgMuuexf0wREzsoB2//9k=",
  },
  {
    src: `${PATH_PHOTOGRAPHY_IMAGES}/Biodome-1-19-25.jpg`,
    alt: "A picture of the Biodome in Montreal, Canada.",
    location: "Montreal, Canada",
    year: "2025",
    size: [3024, 4032],
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAKAAoDASIAAhEBAxEB/8QAFAABAAAAAAAAAAAAAAAAAAAABf/EACUQAAECBQIHAQAAAAAAAAAAAAECAwAEBQYREiETIiMyQVORof/EABQBAQAAAAAAAAAAAAAAAAAAAAT/xAAXEQEBAQEAAAAAAAAAAAAAAAABABEh/9oADAMBAAIRAxEAPwAtNt0p2g1CedcTxA23oJONxgqH7iDZmSlBMuhtWUBZ0nHjMDUDqWfcC3OdWWN1bnvgMuuexf0wREzsoB2//9k=",
  },
  {
    src: `${PATH_PHOTOGRAPHY_IMAGES}/BunkerHill-12-15-24.jpg`,
    alt: "A picture of the Bunker Hill Monument in Boston, United States.",
    location: "Boston, United States",
    year: "2024",
    size: [3024, 4032],
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAKAAoDASIAAhEBAxEB/8QAFAABAAAAAAAAAAAAAAAAAAAABf/EACUQAAECBQIHAQAAAAAAAAAAAAECAwAEBQYREiETIiMyQVORof/EABQBAQAAAAAAAAAAAAAAAAAAAAT/xAAXEQEBAQEAAAAAAAAAAAAAAAABABEh/9oADAMBAAIRAxEAPwAtNt0p2g1CedcTxA23oJONxgqH7iDZmSlBMuhtWUBZ0nHjMDUDqWfcC3OdWWN1bnvgMuuexf0wREzsoB2//9k=",
  },
  {
    src: `${PATH_PHOTOGRAPHY_IMAGES}/Charlestown-12-15-24.jpg`,
    alt: "A picture of the Charlestown Navy Yard in Boston, United States.",
    location: "Boston, United States",
    year: "2024",
    size: [3024, 4032],
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAKAAoDASIAAhEBAxEB/8QAFAABAAAAAAAAAAAAAAAAAAAABf/EACUQAAECBQIHAQAAAAAAAAAAAAECAwAEBQYREiETIiMyQVORof/EABQBAQAAAAAAAAAAAAAAAAAAAAT/xAAXEQEBAQEAAAAAAAAAAAAAAAABABEh/9oADAMBAAIRAxEAPwAtNt0p2g1CedcTxA23oJONxgqH7iDZmSlBMuhtWUBZ0nHjMDUDqWfcC3OdWWN1bnvgMuuexf0wREzsoB2//9k=",
  },
  {
    src: `${PATH_PHOTOGRAPHY_IMAGES}/Church-9-8-24.jpg`,
    alt: "A picture of a church field in Waterloo, Canada.",
    location: "Waterloo, Canada",
    year: "2024",
    size: [3024, 4032],
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAKAAoDASIAAhEBAxEB/8QAFAABAAAAAAAAAAAAAAAAAAAABf/EACUQAAECBQIHAQAAAAAAAAAAAAECAwAEBQYREiETIiMyQVORof/EABQBAQAAAAAAAAAAAAAAAAAAAAT/xAAXEQEBAQEAAAAAAAAAAAAAAAABABEh/9oADAMBAAIRAxEAPwAtNt0p2g1CedcTxA23oJONxgqH7iDZmSlBMuhtWUBZ0nHjMDUDqWfcC3OdWWN1bnvgMuuexf0wREzsoB2//9k=",
  },
  {
    src: `${PATH_PHOTOGRAPHY_IMAGES}/Citadel-3-22-25.jpg`,
    alt: "A picture of a Notre Dame in Montreal, Canada.",
    location: "Montreal, Canada",
    year: "2025",
    size: [3024, 4032],
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAKAAoDASIAAhEBAxEB/8QAFAABAAAAAAAAAAAAAAAAAAAABf/EACUQAAECBQIHAQAAAAAAAAAAAAECAwAEBQYREiETIiMyQVORof/EABQBAQAAAAAAAAAAAAAAAAAAAAT/xAAXEQEBAQEAAAAAAAAAAAAAAAABABEh/9oADAMBAAIRAxEAPwAtNt0p2g1CedcTxA23oJONxgqH7iDZmSlBMuhtWUBZ0nHjMDUDqWfcC3OdWWN1bnvgMuuexf0wREzsoB2//9k=",
  },
  {
    src: `${PATH_PHOTOGRAPHY_IMAGES}/ClockTower-6-21-24.jpg`,
    alt: "A picture of a clock tower in Montreal, Canada.",
    location: "Montreal, Canada",
    year: "2024",
    size: [3024, 4032],
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAKAAoDASIAAhEBAxEB/8QAFAABAAAAAAAAAAAAAAAAAAAABf/EACUQAAECBQIHAQAAAAAAAAAAAAECAwAEBQYREiETIiMyQVORof/EABQBAQAAAAAAAAAAAAAAAAAAAAT/xAAXEQEBAQEAAAAAAAAAAAAAAAABABEh/9oADAMBAAIRAxEAPwAtNt0p2g1CedcTxA23oJONxgqH7iDZmSlBMuhtWUBZ0nHjMDUDqWfcC3OdWWN1bnvgMuuexf0wREzsoB2//9k=",
  },
  {
    src: `${PATH_PHOTOGRAPHY_IMAGES}/Constitution-12-15-24.jpg`,
    alt: "A picture of the USS Constitution in Boston, United States.",
    location: "Boston, United States",
    year: "2024",
    size: [3024, 4032],
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAKAAoDASIAAhEBAxEB/8QAFAABAAAAAAAAAAAAAAAAAAAABf/EACUQAAECBQIHAQAAAAAAAAAAAAECAwAEBQYREiETIiMyQVORof/EABQBAQAAAAAAAAAAAAAAAAAAAAT/xAAXEQEBAQEAAAAAAAAAAAAAAAABABEh/9oADAMBAAIRAxEAPwAtNt0p2g1CedcTxA23oJONxgqH7iDZmSlBMuhtWUBZ0nHjMDUDqWfcC3OdWWN1bnvgMuuexf0wREzsoB2//9k=",
  },
  {
    src: `${PATH_PHOTOGRAPHY_IMAGES}/DP-10-22-24.jpg`,
    alt: "A picture of a DP in Waterloo, Canada.",
    location: "Waterloo, Canada",
    year: "2024",
    size: [4032, 3024],
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAKAAoDASIAAhEBAxEB/8QAFAABAAAAAAAAAAAAAAAAAAAABf/EACUQAAECBQIHAQAAAAAAAAAAAAECAwAEBQYREiETIiMyQVORof/EABQBAQAAAAAAAAAAAAAAAAAAAAT/xAAXEQEBAQEAAAAAAAAAAAAAAAABABEh/9oADAMBAAIRAxEAPwAtNt0p2g1CedcTxA23oJONxgqH7iDZmSlBMuhtWUBZ0nHjMDUDqWfcC3OdWWN1bnvgMuuexf0wREzsoB2//9k=",
  },
  {
    src: `${PATH_PHOTOGRAPHY_IMAGES}/Echo-5-2-24.jpg`,
    alt: "A picture of a Dog in Niagara, Canada.",
    location: "Niagara, Canada",
    year: "2024",
    size: [2496, 2343],
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAKAAoDASIAAhEBAxEB/8QAFAABAAAAAAAAAAAAAAAAAAAABf/EACUQAAECBQIHAQAAAAAAAAAAAAECAwAEBQYREiETIiMyQVORof/EABQBAQAAAAAAAAAAAAAAAAAAAAT/xAAXEQEBAQEAAAAAAAAAAAAAAAABABEh/9oADAMBAAIRAxEAPwAtNt0p2g1CedcTxA23oJONxgqH7iDZmSlBMuhtWUBZ0nHjMDUDqWfcC3OdWWN1bnvgMuuexf0wREzsoB2//9k=",
  },
  {
    src: `${PATH_PHOTOGRAPHY_IMAGES}/Frederiksborg-10-15-24.jpg`,
    alt: "A picture of Frederiksborg Castle in Hillerød, Denmark.",
    location: "Hillerød, Denmark",
    year: "2024",
    size: [3024, 4032],
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAKAAoDASIAAhEBAxEB/8QAFAABAAAAAAAAAAAAAAAAAAAABf/EACUQAAECBQIHAQAAAAAAAAAAAAECAwAEBQYREiETIiMyQVORof/EABQBAQAAAAAAAAAAAAAAAAAAAAT/xAAXEQEBAQEAAAAAAAAAAAAAAAABABEh/9oADAMBAAIRAxEAPwAtNt0p2g1CedcTxA23oJONxgqH7iDZmSlBMuhtWUBZ0nHjMDUDqWfcC3OdWWN1bnvgMuuexf0wREzsoB2//9k=",
  },
  {
    src: `${PATH_PHOTOGRAPHY_IMAGES}/Geodesic-3-22-25.jpg`,
    alt: "A picture of a the Biodome in Montreal, Canada.",
    location: "Montreal, Canada",
    year: "2025",
    size: [3024, 4032],
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAKAAoDASIAAhEBAxEB/8QAFAABAAAAAAAAAAAAAAAAAAAABf/EACUQAAECBQIHAQAAAAAAAAAAAAECAwAEBQYREiETIiMyQVORof/EABQBAQAAAAAAAAAAAAAAAAAAAAT/xAAXEQEBAQEAAAAAAAAAAAAAAAABABEh/9oADAMBAAIRAxEAPwAtNt0p2g1CedcTxA23oJONxgqH7iDZmSlBMuhtWUBZ0nHjMDUDqWfcC3OdWWN1bnvgMuuexf0wREzsoB2//9k=",
  },
  {
    src: `${PATH_PHOTOGRAPHY_IMAGES}/George-12-14-24.jpg`,
    alt: "A picture of a statue of George Washington in Boston, United States.",
    location: "Boston, United States",
    year: "2024",
    size: [3024, 4032],
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAKAAoDASIAAhEBAxEB/8QAFAABAAAAAAAAAAAAAAAAAAAABf/EACUQAAECBQIHAQAAAAAAAAAAAAECAwAEBQYREiETIiMyQVORof/EABQBAQAAAAAAAAAAAAAAAAAAAAT/xAAXEQEBAQEAAAAAAAAAAAAAAAABABEh/9oADAMBAAIRAxEAPwAtNt0p2g1CedcTxA23oJONxgqH7iDZmSlBMuhtWUBZ0nHjMDUDqWfcC3OdWWN1bnvgMuuexf0wREzsoB2//9k=",
  },
  {
    src: `${PATH_PHOTOGRAPHY_IMAGES}/GrandRiver-10-27-24.jpg`,
    alt: "A picture of the Grand River in Waterloo, Canada.",
    location: "Waterloo, Canada",
    year: "2024",
    size: [4032, 3024],
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAKAAoDASIAAhEBAxEB/8QAFAABAAAAAAAAAAAAAAAAAAAABf/EACUQAAECBQIHAQAAAAAAAAAAAAECAwAEBQYREiETIiMyQVORof/EABQBAQAAAAAAAAAAAAAAAAAAAAT/xAAXEQEBAQEAAAAAAAAAAAAAAAABABEh/9oADAMBAAIRAxEAPwAtNt0p2g1CedcTxA23oJONxgqH7iDZmSlBMuhtWUBZ0nHjMDUDqWfcC3OdWWN1bnvgMuuexf0wREzsoB2//9k=",
  },
  {
    src: `${PATH_PHOTOGRAPHY_IMAGES}/GrandRoue-2-12-25.jpg`,
    alt: "A picture of the Grand Roue in Montreal, Canada.",
    location: "Montreal, Canada",
    year: "2025",
    size: [3024, 4032],
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAKAAoDASIAAhEBAxEB/8QAFAABAAAAAAAAAAAAAAAAAAAABf/EACUQAAECBQIHAQAAAAAAAAAAAAECAwAEBQYREiETIiMyQVORof/EABQBAQAAAAAAAAAAAAAAAAAAAAT/xAAXEQEBAQEAAAAAAAAAAAAAAAABABEh/9oADAMBAAIRAxEAPwAtNt0p2g1CedcTxA23oJONxgqH7iDZmSlBMuhtWUBZ0nHjMDUDqWfcC3OdWWN1bnvgMuuexf0wREzsoB2//9k=",
  },
  {
    src: `${PATH_PHOTOGRAPHY_IMAGES}/Grundtvig-10-15-24.jpg`,
    alt: "A picture of a statue of the Grundtvig Church in Copenhagen, Denmark.",
    location: "Copenhagen, Denmark",
    year: "2024",
    size: [3024, 4032],
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAKAAoDASIAAhEBAxEB/8QAFAABAAAAAAAAAAAAAAAAAAAABf/EACUQAAECBQIHAQAAAAAAAAAAAAECAwAEBQYREiETIiMyQVORof/EABQBAQAAAAAAAAAAAAAAAAAAAAT/xAAXEQEBAQEAAAAAAAAAAAAAAAABABEh/9oADAMBAAIRAxEAPwAtNt0p2g1CedcTxA23oJONxgqH7iDZmSlBMuhtWUBZ0nHjMDUDqWfcC3OdWWN1bnvgMuuexf0wREzsoB2//9k=",
  },
  {
    src: `${PATH_PHOTOGRAPHY_IMAGES}/Hedge-10-17-24.jpg`,
    alt: "A picture of a statue of the Hedge in Copenhagen, Denmark.",
    location: "Copenhagen, Denmark",
    year: "2024",
    size: [3024, 4032],
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAKAAoDASIAAhEBAxEB/8QAFAABAAAAAAAAAAAAAAAAAAAABf/EACUQAAECBQIHAQAAAAAAAAAAAAECAwAEBQYREiETIiMyQVORof/EABQBAQAAAAAAAAAAAAAAAAAAAAT/xAAXEQEBAQEAAAAAAAAAAAAAAAABABEh/9oADAMBAAIRAxEAPwAtNt0p2g1CedcTxA23oJONxgqH7iDZmSlBMuhtWUBZ0nHjMDUDqWfcC3OdWWN1bnvgMuuexf0wREzsoB2//9k=",
  },
  {
    src: `${PATH_PHOTOGRAPHY_IMAGES}/IsabellaStewart-12-16-24.jpg`,
    alt: "A picture of a statue of the Isabella Stewart Gardner Museum in Boston, United States.",
    location: "Boston, United States",
    year: "2024",
    size: [3024, 4032],
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAKAAoDASIAAhEBAxEB/8QAFAABAAAAAAAAAAAAAAAAAAAABf/EACUQAAECBQIHAQAAAAAAAAAAAAECAwAEBQYREiETIiMyQVORof/EABQBAQAAAAAAAAAAAAAAAAAAAAT/xAAXEQEBAQEAAAAAAAAAAAAAAAABABEh/9oADAMBAAIRAxEAPwAtNt0p2g1CedcTxA23oJONxgqH7iDZmSlBMuhtWUBZ0nHjMDUDqWfcC3OdWWN1bnvgMuuexf0wREzsoB2//9k=",
  },
  {
    src: `${PATH_PHOTOGRAPHY_IMAGES}/Ladybug-10-18-24.jpg`,
    alt: "A picture of a Ladybug in Copenhagen, Denmark.",
    location: "Copenhagen, Denmark",
    year: "2024",
    size: [3024, 4032],
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAKAAoDASIAAhEBAxEB/8QAFAABAAAAAAAAAAAAAAAAAAAABf/EACUQAAECBQIHAQAAAAAAAAAAAAECAwAEBQYREiETIiMyQVORof/EABQBAQAAAAAAAAAAAAAAAAAAAAT/xAAXEQEBAQEAAAAAAAAAAAAAAAABABEh/9oADAMBAAIRAxEAPwAtNt0p2g1CedcTxA23oJONxgqH7iDZmSlBMuhtWUBZ0nHjMDUDqWfcC3OdWWN1bnvgMuuexf0wREzsoB2//9k=",
  },
  {
    src: `${PATH_PHOTOGRAPHY_IMAGES}/Lighthouse-4-20-25.jpg`,
    alt: "A picture of a lighthouse in Oakville, Canada.",
    location: "Oakville, Canada",
    year: "2024",
    size: [3024, 4032],
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAKAAoDASIAAhEBAxEB/8QAFAABAAAAAAAAAAAAAAAAAAAABf/EACUQAAECBQIHAQAAAAAAAAAAAAECAwAEBQYREiETIiMyQVORof/EABQBAQAAAAAAAAAAAAAAAAAAAAT/xAAXEQEBAQEAAAAAAAAAAAAAAAABABEh/9oADAMBAAIRAxEAPwAtNt0p2g1CedcTxA23oJONxgqH7iDZmSlBMuhtWUBZ0nHjMDUDqWfcC3OdWWN1bnvgMuuexf0wREzsoB2//9k=",
  },
  {
    src: `${PATH_PHOTOGRAPHY_IMAGES}/Marineland-8-28-24.jpg`,
    alt: "A picture of Marineland in Niagara Falls, Canada.",
    location: "Niagara Falls, Canada",
    year: "2024",
    size: [3024, 4032],
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAKAAoDASIAAhEBAxEB/8QAFAABAAAAAAAAAAAAAAAAAAAABf/EACUQAAECBQIHAQAAAAAAAAAAAAECAwAEBQYREiETIiMyQVORof/EABQBAQAAAAAAAAAAAAAAAAAAAAT/xAAXEQEBAQEAAAAAAAAAAAAAAAABABEh/9oADAMBAAIRAxEAPwAtNt0p2g1CedcTxA23oJONxgqH7iDZmSlBMuhtWUBZ0nHjMDUDqWfcC3OdWWN1bnvgMuuexf0wREzsoB2//9k=",
  },
  {
    src: `${PATH_PHOTOGRAPHY_IMAGES}/Metro-10-17-25.jpg`,
    alt: "A picture of the metro in Copenhagen, Denmark.",
    location: "Copenhagen, Denmark",
    year: "2024",
    size: [3024, 4032],
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAKAAoDASIAAhEBAxEB/8QAFAABAAAAAAAAAAAAAAAAAAAABf/EACUQAAECBQIHAQAAAAAAAAAAAAECAwAEBQYREiETIiMyQVORof/EABQBAQAAAAAAAAAAAAAAAAAAAAT/xAAXEQEBAQEAAAAAAAAAAAAAAAABABEh/9oADAMBAAIRAxEAPwAtNt0p2g1CedcTxA23oJONxgqH7iDZmSlBMuhtWUBZ0nHjMDUDqWfcC3OdWWN1bnvgMuuexf0wREzsoB2//9k=",
  },
  {
    src: `${PATH_PHOTOGRAPHY_IMAGES}/Murder-1-16-25.jpg`,
    alt: "A picture of a lamppost in Montreal, Canada.",
    location: "Montreal, Canada",
    year: "2025",
    size: [3024, 4032],
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAKAAoDASIAAhEBAxEB/8QAFAABAAAAAAAAAAAAAAAAAAAABf/EACUQAAECBQIHAQAAAAAAAAAAAAECAwAEBQYREiETIiMyQVORof/EABQBAQAAAAAAAAAAAAAAAAAAAAT/xAAXEQEBAQEAAAAAAAAAAAAAAAABABEh/9oADAMBAAIRAxEAPwAtNt0p2g1CedcTxA23oJONxgqH7iDZmSlBMuhtWUBZ0nHjMDUDqWfcC3OdWWN1bnvgMuuexf0wREzsoB2//9k=",
  },
  {
    src: `${PATH_PHOTOGRAPHY_IMAGES}/NotreDame-1-4-25.jpg`,
    alt: "A picture of a Notre Dame in Montreal, Canada.",
    location: "Montreal, Canada",
    year: "2025",
    size: [3024, 4032],
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAKAAoDASIAAhEBAxEB/8QAFAABAAAAAAAAAAAAAAAAAAAABf/EACUQAAECBQIHAQAAAAAAAAAAAAECAwAEBQYREiETIiMyQVORof/EABQBAQAAAAAAAAAAAAAAAAAAAAT/xAAXEQEBAQEAAAAAAAAAAAAAAAABABEh/9oADAMBAAIRAxEAPwAtNt0p2g1CedcTxA23oJONxgqH7iDZmSlBMuhtWUBZ0nHjMDUDqWfcC3OdWWN1bnvgMuuexf0wREzsoB2//9k=",
  },
  {
    src: `${PATH_PHOTOGRAPHY_IMAGES}/Pier-10-18-24.jpg`,
    alt: "A picture of a pier in Malmo, Sweden.",
    location: "Malmo, Sweden",
    year: "2024",
    size: [4032, 3024],
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAKAAoDASIAAhEBAxEB/8QAFAABAAAAAAAAAAAAAAAAAAAABf/EACUQAAECBQIHAQAAAAAAAAAAAAECAwAEBQYREiETIiMyQVORof/EABQBAQAAAAAAAAAAAAAAAAAAAAT/xAAXEQEBAQEAAAAAAAAAAAAAAAABABEh/9oADAMBAAIRAxEAPwAtNt0p2g1CedcTxA23oJONxgqH7iDZmSlBMuhtWUBZ0nHjMDUDqWfcC3OdWWN1bnvgMuuexf0wREzsoB2//9k=",
  },
  {
    src: `${PATH_PHOTOGRAPHY_IMAGES}/PlantWall-5-12-24.jpg`,
    alt: "A picture of a plant wall in Waterloo, Canada.",
    location: "Waterloo, Canada",
    year: "2024",
    size: [3024, 4032],
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAKAAoDASIAAhEBAxEB/8QAFAABAAAAAAAAAAAAAAAAAAAABf/EACUQAAECBQIHAQAAAAAAAAAAAAECAwAEBQYREiETIiMyQVORof/EABQBAQAAAAAAAAAAAAAAAAAAAAT/xAAXEQEBAQEAAAAAAAAAAAAAAAABABEh/9oADAMBAAIRAxEAPwAtNt0p2g1CedcTxA23oJONxgqH7iDZmSlBMuhtWUBZ0nHjMDUDqWfcC3OdWWN1bnvgMuuexf0wREzsoB2//9k=",
  }
]