import { MasonryImage } from "@/components/common/photos/MasonryLayout";
import { PATH_PHOTOGRAPHY_IMAGES } from "@/lib/constants";

export const photos: MasonryImage[] = [
  {
    src: `${PATH_PHOTOGRAPHY_IMAGES}/Angel-3-15-25.jpg`,
    alt: "A picture of an angel statue in a park in Montreal, Canada.",
    location: "Montreal, Canada",
    year: "2025",
    size: [3024, 4032],
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAKAAoDASIAAhEBAxEB/8QAFAABAAAAAAAAAAAAAAAAAAAABf/EACUQAAECBQIHAQAAAAAAAAAAAAECAwAEBQYREiETIiMyQVORof/EABQBAQAAAAAAAAAAAAAAAAAAAAT/xAAXEQEBAQEAAAAAAAAAAAAAAAABABEh/9oADAMBAAIRAxEAPwAtNt0p2g1CedcTxA23oJONxgqH7iDZmSlBMuhtWUBZ0nHjMDUDqWfcC3OdWWN1bnvgMuuexf0wREzsoB2//9k=",
  },
  {
    src: `${PATH_PHOTOGRAPHY_IMAGES}/Athena-10-17-24.jpg`,
    alt: "A picture of an Athena statue in Copenhagen, Denmark.",
    location: "Copenhagen, Denmark",
    year: "2024",
    size: [3024, 4032],
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAKAAoDASIAAhEBAxEB/8QAFAABAAAAAAAAAAAAAAAAAAAABf/EACUQAAECBQIHAQAAAAAAAAAAAAECAwAEBQYREiETIiMyQVORof/EABQBAQAAAAAAAAAAAAAAAAAAAAT/xAAXEQEBAQEAAAAAAAAAAAAAAAABABEh/9oADAMBAAIRAxEAPwAtNt0p2g1CedcTxA23oJONxgqH7iDZmSlBMuhtWUBZ0nHjMDUDqWfcC3OdWWN1bnvgMuuexf0wREzsoB2//9k=",
  },
  {
    src: `${PATH_PHOTOGRAPHY_IMAGES}/Beluga-8-28-24.jpg`,
    alt: "A picture of a Beluga whale at Marineland in Niagara Falls, Canada.",
    location: "Niagara Falls, Canada",
    year: "2024",
    size: [3024, 4032],
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAKAAoDASIAAhEBAxEB/8QAFAABAAAAAAAAAAAAAAAAAAAABf/EACUQAAECBQIHAQAAAAAAAAAAAAECAwAEBQYREiETIiMyQVORof/EABQBAQAAAAAAAAAAAAAAAAAAAAT/xAAXEQEBAQEAAAAAAAAAAAAAAAABABEh/9oADAMBAAIRAxEAPwAtNt0p2g1CedcTxA23oJONxgqH7iDZmSlBMuhtWUBZ0nHjMDUDqWfcC3OdWWN1bnvgMuuexf0wREzsoB2//9k=",
  },
  {
    src: `${PATH_PHOTOGRAPHY_IMAGES}/Biodome-1-19-25.jpg`,
    alt: "A picture of the Biodome in Montreal, Canada.",
    location: "Montreal, Canada",
    year: "2025",
    size: [3024, 4032],
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAKAAoDASIAAhEBAxEB/8QAFAABAAAAAAAAAAAAAAAAAAAABf/EACUQAAECBQIHAQAAAAAAAAAAAAECAwAEBQYREiETIiMyQVORof/EABQBAQAAAAAAAAAAAAAAAAAAAAT/xAAXEQEBAQEAAAAAAAAAAAAAAAABABEh/9oADAMBAAIRAxEAPwAtNt0p2g1CedcTxA23oJONxgqH7iDZmSlBMuhtWUBZ0nHjMDUDqWfcC3OdWWN1bnvgMuuexf0wREzsoB2//9k=",
  },
  {
    src: `${PATH_PHOTOGRAPHY_IMAGES}/BunkerHill-12-15-24.jpg`,
    alt: "A picture of the Bunker Hill Monument in Boston, United States.",
    location: "Boston, United States",
    year: "2024",
    size: [3024, 4032],
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAKAAoDASIAAhEBAxEB/8QAFAABAAAAAAAAAAAAAAAAAAAABf/EACUQAAECBQIHAQAAAAAAAAAAAAECAwAEBQYREiETIiMyQVORof/EABQBAQAAAAAAAAAAAAAAAAAAAAT/xAAXEQEBAQEAAAAAAAAAAAAAAAABABEh/9oADAMBAAIRAxEAPwAtNt0p2g1CedcTxA23oJONxgqH7iDZmSlBMuhtWUBZ0nHjMDUDqWfcC3OdWWN1bnvgMuuexf0wREzsoB2//9k=",
  },
  {
    src: `${PATH_PHOTOGRAPHY_IMAGES}/Charlestown-12-15-24.jpg`,
    alt: "A picture of the Charlestown Navy Yard in Boston, United States.",
    location: "Boston, United States",
    year: "2024",
    size: [3024, 4032],
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAKAAoDASIAAhEBAxEB/8QAFAABAAAAAAAAAAAAAAAAAAAABf/EACUQAAECBQIHAQAAAAAAAAAAAAECAwAEBQYREiETIiMyQVORof/EABQBAQAAAAAAAAAAAAAAAAAAAAT/xAAXEQEBAQEAAAAAAAAAAAAAAAABABEh/9oADAMBAAIRAxEAPwAtNt0p2g1CedcTxA23oJONxgqH7iDZmSlBMuhtWUBZ0nHjMDUDqWfcC3OdWWN1bnvgMuuexf0wREzsoB2//9k=",
  },
  {
    src: `${PATH_PHOTOGRAPHY_IMAGES}/Church-9-8-24.jpg`,
    alt: "A picture of a church field in Waterloo, Canada.",
    location: "Waterloo, Canada",
    year: "2024",
    size: [3024, 4032],
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAKAAoDASIAAhEBAxEB/8QAFAABAAAAAAAAAAAAAAAAAAAABf/EACUQAAECBQIHAQAAAAAAAAAAAAECAwAEBQYREiETIiMyQVORof/EABQBAQAAAAAAAAAAAAAAAAAAAAT/xAAXEQEBAQEAAAAAAAAAAAAAAAABABEh/9oADAMBAAIRAxEAPwAtNt0p2g1CedcTxA23oJONxgqH7iDZmSlBMuhtWUBZ0nHjMDUDqWfcC3OdWWN1bnvgMuuexf0wREzsoB2//9k=",
  }
]